exports.SUBSCRIPTION_TRIAL = "TR";
exports.SUBSCRIPTION_ACTIVE = "ACT";
exports.SUBSCRIPTION_PENDING = "PEN";
exports.SUBSCRIPTION_EXPIRED = "EXP";
exports.GCM_SERVER_KEY = "AIzaSyBcCpi6Ux4RC4kDfwkJBqKY_ldA00JuikM";